### ISSUE TITLE
If the service recognises that there is a "?", how to deal with it?

### ISSUE THREAD

**Issue by Caratpine** [Ullaakut/nmap#116]
Hi,

The results of my scan using Nmap in the shell are as follows,
<img width="302" alt="image" src="https://github.com/Ullaakut/nmap/assets/11403002/2a79e0b4-c9bd-4670-a133-782b185c81b3">

and the results of my program using this library are as follows,
<img width="426" alt="image" src="https://github.com/Ullaakut/nmap/assets/11403002/b249f124-524c-4c96-bcea-fcc8096a255b">

You can see that one has a "?" and the other does not have a question mark. What is going on with this? Thanks.

**Comment by Ullaakut** [comment]
Hi @Caratpine! Interesting find. I've never had this happen during my scans. May I ask, do you know how to reproduce this? Could you send me the full (obfuscated) XML file to look for any way to identify this difference?

If it turns out the XML file shows no distinction, we might have to contribute to the nmap binary itself to add it.

**Comment by Caratpine** [comment]
Hi, @Ullaakut , thanks for your reply.
Yes, sure! Here is the XML content:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE nmaprun>
<?xml-stylesheet href="file:///usr/local/bin/../share/nmap/nmap.xsl" type="text/xsl"?>
<!-- Nmap 7.93 scan initiated Sat Jun 17 22:38:10 2023 as: /usr/local/bin/nmap -p 80 -Pn -sV -n -&#45;open -T4 -sT -oX ./nmap.xml 127.0.0.1 -->
<nmaprun scanner="nmap" args="/usr/local/bin/nmap -p 80 -Pn -sV -n -&#45;open -T4 -sT -oX ./nmap.xml 127.0.0.1" start="1687012690" startstr="Sat Jun 17 22:38:10 2023" version="7.93" xmloutputversion="1.05">
	<scaninfo type="connect" protocol="tcp" numservices="1" services="80"/>
	<verbose level="0"/>
	<debugging level="0"/>
	<taskprogress task="Connect Scan" time="1687012691" percent="100.00" remaining="0" etc="1687012691"/>
	<taskprogress task="Service scan" time="1687012735" percent="0.00"/>
	<host starttime="1687012691" endtime="1687012751">
		<status state="up" reason="user-set" reason_ttl="0"/>
		<address addr="127.0.0.1" addrtype="ipv4"/>
		<hostnames>
		</hostnames>
		<ports>
			<port protocol="tcp" portid="80">
				<state state="open" reason="syn-ack" reason_ttl="0"/>
				<service name="http" servicefp="SF-Port80-TCP:V=7.93%I=7%D=6/17%Time=648DC559%P=x86_64-apple-darwin21.5.0%r(RTSPRequest,A6,&quot;&lt;html&gt;\r\n&lt;head&gt;&lt;title&gt;400\x20Bad\x20Request&lt;/title&gt;&lt;/head&gt;\r\n&lt;body&gt;\r\n&lt;center&gt;&lt;h1&gt;400\x20Bad\x20Request&lt;/h1&gt;&lt;/center&gt;\r\n&lt;hr&gt;&lt;center&gt;nginx/1\.18\.0\x20\(Ubuntu\)&lt;/center&gt;\r\n&lt;/body&gt;\r\n&lt;/html&gt;\r\n&quot;);" method="table" conf="3"/>
			</port>
		</ports>
		<times srtt="8541" rttvar="8541" to="100000"/>
	</host>
	<runstats>
		<finished time="1687012751" timestr="Sat Jun 17 22:39:11 2023" summary="Nmap done at Sat Jun 17 22:39:11 2023; 1 IP address (1 host up) scanned in 60.83 seconds" elapsed="60.83" exit="success"/>
		<hosts up="1" down="0" total="1"/>
	</runstats>
</nmaprun>
```
nmap command:
```
/usr/local/bin/nmap 127.0.0.1 -p 80 -Pn -sV -n --open -T4 -sT
```
nmap version: 7.93
OS system: macOS

I saw that there is an attribute in the **Service** structure called **Confidence**, how do I understand this? The higher the value, the more accurate the recognition?

**Comment by Ullaakut** [comment]
@Caratpine Indeed, the `?` is the visual representation of that `conf` value. Confidence is not very high, therefore a `?` symbol is shown.

[This attribute is already supported by this library](https://github.com/Ullaakut/nmap/blob/master/xml.go#L249) so you can use that in order to detect low confidence service discovery :)

I hope that answers your question, feel free to reopen this issue if anything is left unclear! Have a nice day!

**Comment by Caratpine** [comment]
Thanks @Ullaakut, your reply helped me a lot!
