### ISSUE TITLE
XML to JSON  support

### ISSUE THREAD

**Issue by varsraja** [Ullaakut/nmap#118]
I would like to know , if we can get the xml output from nmap scan and store it in a file.
At a later point, read the XML file and get json output. 

Additionally, is it possible to do a diff between 2 consecutive nmap runs using the library or should i use something like ndiff.

**Comment by Ullaakut** [comment]
Hi, you can of course use the XML output from nmap, generated with this wrapper. To turn it into JSON though, you will need to use third party tools I'm afraid.

In order to do that, use [`scanner.ToFile`](https://github.com/Ullaakut/nmap/blob/master/nmap.go#L82-L87) to write the output of the scan to a file of your choosing.
