### ISSUE TITLE
Support the `WithInterfaceList` option

### ISSUE THREAD

**Issue by gakkiyomi** [Ullaakut/nmap#59]
![image](https://user-images.githubusercontent.com/41406557/95540327-1e18b180-0a23-11eb-81f8-4208287111d4.png)
![image](https://user-images.githubusercontent.com/41406557/95540351-2a9d0a00-0a23-11eb-87d1-caf3cbb40ac2.png)

**Comment by Ullaakut** [comment]
Hi @gakkiyomi ! Thanks, I'll look into this :) It's probably an issue with the XML models not taking something into account there, not sure why though.

**Comment by gakkiyomi** [comment]
> Hi @gakkiyomi ! Thanks, I'll look into this :) It's probably an issue with the XML models not taking something into account there, not sure why though.

@Ullaakut Unfortunately i use nmap --iflist -oX 192.168.1.222 command also canot get response too !

**Comment by Ullaakut** [comment]
I think I see the problem. Nmap doesn't seem to support the `-oX` mode along with `--iflist`. Instead of outputting XML, it outputs in a completely different format which cannot be parsed by this library (as of now).

I guess we can then transform this ticket into a feature request for the support of parsing the output of the `--iflist` option, but I won't have time to do it myself now :(

**Comment by gakkiyomi** [comment]
> I think I see the problem. Nmap doesn't seem to support the `-oX` mode along with `--iflist`. Instead of outputting XML, it outputs in a completely different format which cannot be parsed by this library (as of now).
> 
> I guess we can then transform this ticket into a feature request for the support of parsing the output of the `--iflist` option, but I won't have time to do it myself now :(

in my opnion, can use antrl4 parse --iflist output
