### ISSUE TITLE
github.com/Ullaakut/nmap/v2/pkg/osfamilies: not found

### ISSUE THREAD

**Issue by blshkv** [Ullaakut/nmap#78]
I'm creating a custom build script for Pentoo using standard Gentoo ebuild and golang-vcs-snapshot eclass.

Currently, Cameradar fails to build due to the following error:
```
WORK=/var/tmp/portage/net-analyzer/cameradar-5.0.1-r1/temp/go-build4077822569
src/github.com/ullaakut/cameradar/vendor/github.com/Ullaakut/nmap/xml.go:11:2: cannot find package "github.com/Ullaakut/nmap/v2/pkg/osfamilies" in any of:
        /var/tmp/portage/net-analyzer/cameradar-5.0.1-r1/work/cameradar-5.0.1/src/github.com/ullaakut/cameradar/vendor/github.com/Ullaakut/nmap/v2/pkg/osfamilies (vendor tree)
        /usr/lib/go/src/github.com/Ullaakut/nmap/v2/pkg/osfamilies (from $GOROOT)
        /var/tmp/portage/net-analyzer/cameradar-5.0.1-r1/work/cameradar-5.0.1/src/github.com/Ullaakut/nmap/v2/pkg/osfamilies (from $GOPATH)
        /usr/lib/go-gentoo/src/github.com/Ullaakut/nmap/v2/pkg/osfamilies
src/github.com/ullaakut/cameradar/cmd/cameradar/cameradar.go:10:2: cannot find package "github.com/Ullaakut/cameradar/v5" in any of:
        /var/tmp/portage/net-analyzer/cameradar-5.0.1-r1/work/cameradar-5.0.1/src/github.com/ullaakut/cameradar/vendor/github.com/Ullaakut/cameradar/v5 (vendor tree)
        /usr/lib/go/src/github.com/Ullaakut/cameradar/v5 (from $GOROOT)
        /var/tmp/portage/net-analyzer/cameradar-5.0.1-r1/work/cameradar-5.0.1/src/github.com/Ullaakut/cameradar/v5 (from $GOPATH)
        /usr/lib/go-gentoo/src/github.com/Ullaakut/cameradar/v5
 * ERROR: net-analyzer/cameradar-5.0.1-r1::pentoo failed (compile phase):

```

There are few references which seems broken:
https://github.com/Ullaakut/nmap/blob/master/xml.go#L11
https://github.com/Ullaakut/nmap/blob/master/go.mod#L1

can you create both directories (v2/pkg/osfamilies) or remove v2 and v5 completely?

**Comment by blshkv** [comment]
Also, there are different calls. The release tar.gz file has "github.com/ullaakut/cameradar" structure (low case),
however the package called "github.com/Ullaakut/cameradar"

**Comment by Ullaakut** [comment]
Hi @blshkv !

I'm not sure what the issue is that you are pointing out by linking the go module and the import of the osfamilies package from `xml.go`? It is normal that there isn't a specific go module for the `osfamilies` package. It is a package that is part of the `github.com/Ullaakut/nmap/v2`, as expected.

I don't really understand why your compilation fails. On my end, running `go get github.com/Ullaakut/nmap/v2/pkg/osfamilies` works just fine, and so does building Cameradar both manually and in Docker.

* Which version of go are you using? Are go modules enabled?
* Did you use `go get`/`go mod` to fetch your dependencies, or did you manually download and extract the tar.gz archive? I am pretty sure that using the archive is not going to work.
* Where do you expect the package to be fetched from? Can you show me what it contains?

Removing the go module versions would be a huge breaking change and make most users upset, and creating folders named `v2` and `v5` would also be problematic, as it would conflict with the go module path, so it's not the right solution.

**Comment by blshkv** [comment]
I'm using dev-lang/go-1.16.2, modules are enabled and manually downloaded .tar.gz. It works for any other tools just fine.
It also works fine if I create these symlinks.

Sorry, I'm not a "go" expert. I'm just trying to follow the existing Gentoo API (eclass). But I find these v2 and v5 are very confusing and not consistent with the rest of the packages.

**Comment by Ullaakut** [comment]
Ah, so the way those versions work in modern Go (>1.13) is that there are now modules, which can be versioned, and contain one or more packages. Unfortunately, while this makes version control of multiple dependencies very neat for Go developers, it also means you can no longer just rely on the file system and use the tarballs from GitHub releases.

What you'll need to do if you want to properly download your dependencies is to run [`go mod download`](https://golang.org/ref/mod#go-mod-download) or [`go mod vendor`](https://golang.org/ref/mod#go-mod-vendor).

Let me know if you need more details, but without more context on your build it's difficult to pinpoint you to the exact right direction 😅

**Comment by blshkv** [comment]
There is a new 'go-modules' Gentoo eclass, but the list of dependencies is much longer.
Some modules need to have multiple versions for no real reason. This is crazy.

Ok, nevermind. I'll just symlink whatever I need ;-)

**Comment by blshkv** [comment]
FYI, found a gentoo tool to generate the full list:
https://github.com/williamh/get-ego-vendor
The problem solve ;-)

**Comment by Ullaakut** [comment]
If you are curious about why go modules have multiple versions, I recommend taking a look at https://blog.golang.org/using-go-modules :)
